// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/kevinxvu/vibe-tools/config"
	llm2 "github.com/kevinxvu/vibe-tools/internal/api/service/llm"
	"github.com/kevinxvu/vibe-tools/internal/model"
	"github.com/kevinxvu/vibe-tools/pkg/llm"
	"github.com/kevinxvu/vibe-tools/pkg/llm/genai"
	"github.com/kevinxvu/vibe-tools/pkg/llm/openai"
	"github.com/kevinxvu/vibe-tools/pkg/server"
	"github.com/labstack/echo/v4"
	genai2 "google.golang.org/genai"
)

// Injectors from wire.go:

// InitializeApplication uses wire to build all dependencies
func InitializeApplication() (*Application, error) {
	configuration, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	echo := ProvideServer(configuration)
	auth := ProvideAuth()
	service := ProvideOpenAIService(configuration)
	genaiService, err := ProvideGenAIService(configuration)
	if err != nil {
		return nil, err
	}
	provider, err := ProvideLLMFactory(configuration, service, genaiService)
	if err != nil {
		return nil, err
	}
	llmService := ProvideLLMService(provider)
	application := &Application{
		Config: configuration,
		Server: echo,
		Auth:   auth,
		LLMSvc: llmService,
	}
	return application, nil
}

// wire.go:

// ProvideConfig loads configuration
func ProvideConfig() (*config.Configuration, error) {
	return config.Load()
}

type publicAuth struct{}

func (publicAuth) User(echo.Context) *model.AuthUser {
	return nil
}

// ProvideAuth creates a no-op Auth implementation for public routes.
func ProvideAuth() model.Auth {
	return publicAuth{}
}

// ProvideLLMFactory builds a Factory with all registered providers and returns
// the single active Provider selected by cfg.LLMProvider.
func ProvideLLMFactory(cfg *config.Configuration, openAI *openai.Service, genAI *genai.Service) (llm.Provider, error) {
	f := llm.NewFactory()
	if openAI != nil {
		f.Register(llm.ProviderOpenAI, openAI)
	}
	if genAI != nil {
		f.Register(llm.ProviderGenAI, genAI)
	}
	providerType := llm.ProviderType(cfg.LLMProvider)
	p, err := f.Create(providerType)
	if err != nil {
		return llm.NewDisabledProvider(providerType), nil
	}
	return p, nil
}

// ProvideLLMService creates llm service using the active Provider from the factory.
func ProvideLLMService(p llm.Provider) llm2.Service {
	return llm2.New(p)
}

// ProvideServer creates Echo server
func ProvideServer(cfg *config.Configuration) *echo.Echo {
	return server.New(&server.Config{
		Stage:        cfg.Stage,
		Port:         cfg.Port,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		AllowOrigins: cfg.AllowOrigins,
		Debug:        cfg.Debug,
	})
}

// ProvideOpenAIService creates OpenAI service
func ProvideOpenAIService(cfg *config.Configuration) *openai.Service {
	if cfg.OpenAIAPIKey == "" {
		return nil
	}
	return openai.New(openai.Config{
		APIKey:          cfg.OpenAIAPIKey,
		BaseURL:         cfg.OpenAIBaseURL,
		Timeout:         cfg.LLMTimeout,
		MaxRetries:      cfg.LLMMaxRetries,
		TextModel:       cfg.LLMTextModel,
		AudioModel:      cfg.LLMAudioModel,
		MaxInputTokens:  cfg.LLMMaxInputTokens,
		MaxOutputTokens: cfg.LLMMaxOutputTokens,
		LimitTokenUsage: cfg.LLMLimitTokenUsage,
	})
}

// ProvideGenAIService creates Google GenAI service.
// Returns nil (no error) when no credentials are configured.
// APIKey and Project are mutually exclusive: APIKey is used for Gemini Developer API,
// Project+Location are used for Vertex AI.
func ProvideGenAIService(cfg *config.Configuration) (*genai.Service, error) {
	if cfg.GenAIAPIKey == "" {
		return nil, nil
	}
	genCfg := genai.Config{
		Backend:         genai2.Backend(cfg.GenAIBackend),
		TextModel:       cfg.LLMTextModel,
		Timeout:         cfg.LLMTimeout,
		MaxRetries:      cfg.LLMMaxRetries,
		MaxInputTokens:  cfg.LLMMaxInputTokens,
		MaxOutputTokens: cfg.LLMMaxOutputTokens,
		LimitTokenUsage: cfg.LLMLimitTokenUsage,
		APIKey:          cfg.GenAIAPIKey,
	}
	return genai.New(context.Background(), genCfg)
}

// Application holds all initialized services
type Application struct {
	Config *config.Configuration
	// DB         *gorm.DB           // disabled - no database
	Server *echo.Echo
	Auth   model.Auth
	// AuthSvc    authSvc.Service    // disabled - no database
	// UserSvc    userSvc.Service    // disabled - no database
	// CountrySvc countrySvc.Service // disabled - no database
	LLMSvc llm2.Service
}
